In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from pathlib import Path
import pandas as pd

path = Path.cwd() / 'car' / 'car.data'
print(path)

df = pd.read_csv(path, header=None)
print(df.head())

c:\Users\ASUS\Desktop\code\ML\knn classifier\car\car.data
       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [3]:
df = pd.read_csv('car/car.data', header=None)
type(df)

pandas.DataFrame

In [4]:
df.sample(4)
df.shape

(1728, 7)

In [5]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
df.sample(3)
print(df['buying'].unique())
print(df['maint'].unique())
print(df['doors'].unique())

<StringArray>
['vhigh', 'high', 'med', 'low']
Length: 4, dtype: str
<StringArray>
['vhigh', 'high', 'med', 'low']
Length: 4, dtype: str
<StringArray>
['2', '3', '4', '5more']
Length: 4, dtype: str

In [6]:
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   class     1728 non-null   str
dtypes: str(7)
memory usage: 94.6 KB

In [8]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
for col in col_names:    
    print(df[col].value_counts())

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64
persons
2       576
4       576
more    576
Name: count, dtype: int64
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64
safety
low     576
med     576
high    576
Name: count, dtype: int64
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [9]:
df['safety'].value_counts()

safety
low     576
med     576
high    576
Name: count, dtype: int64

In [10]:
df['safety'].value_counts()

safety
low     576
med     576
high    576
Name: count, dtype: int64

In [11]:
df['class'].value_counts()
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
X = df.drop(['class'], axis=1)
y = df['class']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
X_train.shape, X_test.shape

((1382, 6), (346, 6))

In [16]:
X_train.head()

     buying  maint  doors persons lug_boot safety
107   vhigh  vhigh  5more    more      big   high
901     med  vhigh      3       4    small    med
1709    low    low  5more       2      big   high
706    high    med      4       2      med    med
678    high    med      3       2      med    low

In [17]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [18]:
category_orders=[
    ['low','med','high','vhigh'],
    ['low','med','high','vhigh'],
    ['2', '3', '4', '5more'],        
    ['2', '4', 'more'],                 
    ['small', 'med', 'big'],            
    ['low', 'med', 'high']             
]
encoder = OrdinalEncoder(categories=category_orders,dtype=int)
X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

In [19]:
le=LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [20]:
y_train

array([2, 2, 2, ..., 0, 2, 0], shape=(1382,))

In [21]:
le.classes_

array(['acc', 'good', 'unacc', 'vgood'], dtype=object)

In [22]:
X_train_encoded = pd.DataFrame(X_train_encoded, columns=X_train.columns)
X_test_encoded = pd.DataFrame(X_test_encoded, columns=X_train.columns)
X_train_encoded.head()

   buying  maint  doors  persons  lug_boot  safety
0       3      3      3        2         2       2
1       1      3      1        1         0       1
2       0      0      3        0         2       2
3       2      1      2        0         1       1
4       2      1      1        0         1       0

In [ ]:
X_test_encoded.head()