In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv("Modified_Mobile_Price_Data.csv")

In [4]:
df.sample()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
1864,1220,1,2.8,0,1,0,54,0.7,109,7,...,383,1249,1037,6,4,15,1,0,0,5278

In [5]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 , random_state=0)

In [7]:
X_train.sample(3)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
1573,793,1,1.9,1,0,1,43,0.3,124,8,2,15,1196,1050,11,9,3,1,1,1
1720,1248,0,2.4,0,6,1,9,0.4,89,3,8,71,1686,2454,9,8,13,1,1,0
1928,1283,1,2.4,1,8,1,33,1.0,93,3,15,510,980,773,17,7,2,1,1,0