In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("student-performance.csv")

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.518868,72.341163,74.604843
1,female,group C,some college,standard,completed,69.372786,90.693512,88.434536
2,female,group B,master's degree,standard,none,90.747297,95.972689,93.364383
3,male,group A,associate's degree,free/reduced,none,47.311826,57.336038,44.197319
4,male,group C,some college,standard,none,76.948720,78.920104,75.317157

In [6]:
new_df=df[['reading score' , 'writing score']]
new_df.head()

   reading score  writing score
0      72.341163      74.604843
1      90.693512      88.434536
2      95.972689      93.364383
3      57.336038      44.197319
4      78.920104      75.317157